name: Mobile Reading Data Exchange
title: Mobile Reading Data Exchange
description: "Mobile Reading Data Exchange Project Through TASCHA"
baseurl: "/Mobile-Reading-Data-Exchange"
tagline: ""

# Build settings
markdown: kramdown
plugins: [jekyll-paginate][jekyll-analytics]
paginate: 3
paginate_path: '/page:num/'


