name: Mobile Reading Data Exchange
title: Mobile Reading Data Exchange
description: "Mobile Reading Data Exchange Project Through TASCHA"
baseurl: "/Mobile-Reading-Data-Exchange"
tagline: ""

# Build settings
markdown: kramdown
-plugins: 
-- jekyll-paginate-v2
-paginate: 5
-paginate_path: '/blog/page:num/'

