name: Mobile Reading Data Exchange
title: Mobile Reading Data Exchange
description: "Mobile Reading Data Exchange Project Through TASCHA"
baseurl: "/Mobile-Reading-Data-Exchange"
tagline: ""

# Build settings
<<<<<<< HEAD
plugins: [jekyll-paginate-v2]
# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title_suffix: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
=======
markdown: kramdown
plugins: [jekyll-paginate]
paginate: 5
paginate_path: '/page:num/'
>>>>>>> origin/master

